---
apiVersion: batch/v1
kind: Job
metadata: 
  name: hellojob
spec: 
  template: 
    metadata: 
      name: heyjob
    spec: 
      containers: 
        - name: alpine
          image: alpine
          commands: 
            - sleep
            - 10s  