---
apiVersion: v1
kind: Pod
metadata: 
  name: failure1
spec: 
  restartPolicy: OnFailure
  containers: 
    - name: alpine
      image: alpine
      args: 
        - sleep
        - 3SM

---
apiVersion: v1
kind: Pod
metadata: 
  name: failure2
spec: 
  restartPolicy: OnFailure
  containers: 
    - name: alpine
      image: alpine
      args: 
        - sleep
        - 3s